<!--
		%\VignetteEngine{knitr::docco_linear}
		%\VignetteIndexEntry{Local-EM example with Kentucky}
-->
	

# Local-EM example with Kentucky



```{r setup}

ncores = 1+ (.Platform$OS.type=='unix')

library('localEM')
library('mapmisc')

data('kentuckyCounty') 
data('kentuckyTract')

data('kMap')

# 3000 expected events
kentuckyTract$expected = (3000/sum(kentuckyTract$expected, na.rm=TRUE)) * 
	kentuckyTract$expected
```


 

# Rasters

```{r rasters}
lemRaster = rasterPartition(
		polyCoarse = kentuckyCounty, 
		polyFine = kentuckyTract, 
    cellsCoarse = 6, 
		cellsFine = 100,
    bw = c(12,15,  17, 20, 25) * 1000, 
    ncores = ncores,
		offsetFile = 'off.grd', idFile = 'id.grd'
)

sum(kentuckyTract$expected)
sum(values(lemRaster$offset$offset), na.rm=TRUE)*prod(res(lemRaster$offset))
```



```{r plotOffset, echo=FALSE}
oCol = colourScale(
		lemRaster$offset$offset,
		breaks=10, style='equal',
		dec=8, transform='sqrt'
)
map.new(kentuckyTract)
plot(lemRaster$offset$offset,
		col=oCol$col, breaks=oCol$breaks,
		legend=FALSE, add=TRUE)
plot(kMap, add=TRUE)

legendBreaks("topleft", 
		oCol$breaks*10^6, col=oCol$col,
		title='cases/km2', bg='white')

scaleBar(kentuckyCounty,
		'topleft',
		inset=c(0.3, 0.1),
		bg='white'
)
```



# Simulate cases


```{r simcases}
kLogOffset = log(lemRaster$offset$offset)
names(kLogOffset) = 'logOffset'

set.seed(0)
kCases = geostatsp::simLgcp(
		param=c(mean=0, variance=0.4^2, 
        range=120*1000, shape=2),
		covariates = kLogOffset,
		offset='logOffset')

length(kCases$events)
sum(values(kCases$raster$intensity), na.rm=TRUE)*prod(res(kCases$raster))


countyCounts = table(over(kCases$events, kentuckyCounty)$id)
kentuckyCounty$count = countyCounts[kentuckyCounty$id]
kentuckyCounty$count[is.na(kentuckyCounty$count)]= 0
```



```{r plotCases, fig.cap = 'simulated', fig.subcap = c('intensity','events'), echo=FALSE}
iCol = colourScale(
		kCases$raster$relativeIntensity,
		breaks=8, dec=1, style='equal'
)

map.new(kentuckyTract)
plot(kCases$raster$relativeIntensity,
	col=iCol$col, breaks=iCol$breaks,
legend=FALSE, add=TRUE)
plot(kMap, add=TRUE)
		
legendBreaks("topleft", 
	iCol, title='relative risk',
	bg='white')

scaleBar(kentuckyCounty,
	'topleft',
	inset=c(0.3, 0.1),
	bg='white'
)
		
map.new(kentuckyTract)
plot(kMap, add=TRUE)
points(kCases$events, col='#FF000030')

scaleBar(kentuckyCounty,
	'topleft',
	inset=c(0.3, 0.1),
	bg='white'
)
```

# Smoothing Matrix

```{r smoothingMatrix, cache=TRUE, stuff=0}
lemSmoothMat = smoothingMatrix(
		rasterObjects = lemRaster, 
    ncores = ncores,
		verbose=TRUE) 

dim(lemSmoothMat$smoothingArray)
dimnames(lemSmoothMat$smoothingArray)[[3]]
```



```{r cv}
lemCv = lemXv(x = kentuckyCounty, 
    lemObjects = lemSmoothMat, 
    ncores = ncores) 
bestBw = lemCv$bw[which.min(lemCv$cv)]
```



```{r plotCv, echo=FALSE}
par(mar=c(5,5,1,1))
plot(do.call(cbind, lemCv), xlab='bw', ylab='cv', log='x', pch=16, col='red', type='o')
abline(v=bestBw, lty=3)
```


# Risk estimates

```{r riskExt}
lemRisk = riskEst(
	x = kentuckyCounty,
    lemObjects = lemSmoothMat,
    bw = bestBw
)
```



```{r plotRisk, echo=FALSE}
rCol = colourScale(
		lemRisk,
		breaks=10, style='equal',
		dec=1
)

map.new(kentuckyTract)

plot(lemRisk,
		col=rCol$col, breaks=rCol$breaks,
		legend=FALSE, add=TRUE)

plot(kMap, add=TRUE)

legendBreaks("topleft", 
		rCol,
		title='rr', bg='white')

scaleBar(kentuckyCounty,
		'topleft',
		inset=c(0.3, 0.1),
		bg='white'
)
```


# Exceedance probabilities

```{r excProb}
lemExcProb = excProb(x = kentuckyCounty, 
    lemObjects = lemSmoothMat, 
		estimate=lemRisk,
		bw=bestBw,
    threshold = c(1.25,1.75), 
    Nboot = 200, 
    ncores = ncores) 
```



```{r plotExcProb, echo=FALSE, fig.cap='Exceedance probabilities', fig.subcap=names(lemExcProb)}

pCol = colourScale(
		breaks=c(0,0.2, 0.8, 0.95,1),
		style='fixed',
		col=c('green','yellow','orange','red')
)								


for(Dthreshold in names(lemExcProb)) {
	
	
	map.new(kentuckyTract)
	
	plot(lemExcProb[[Dthreshold]],
			col=pCol$col, breaks=pCol$breaks,
			legend=FALSE, add=TRUE)
	
	plot(kMap, add=TRUE)
	
	legendBreaks("topleft", 
			pCol,
			title=paste('prob, t=', gsub("threshold\\.", '', Dthreshold)),
			bg='white')
	
	scaleBar(kentuckyCounty,
			'topleft',
			inset=c(0.3, 0.1),
			bg='white'
	)
}
```


# ROC

```{r lemRoc}
lemRoc = geostatsp::spatialRoc(
  	fit= lemExcProb, 
  	truth = kCases, 
		border=NULL, random=FALSE,
		prob = NULL, 
  	spec = seq(0,1,by=0.01)
)
```



```{r plotRoc, fig.cap='ROC', echo=FALSE}
matplot(lemRoc[,1], lemRoc[,-1], ylab='sens', 
	xlab='1-spec', type='l', col=2:ncol(lemRoc))
legend("bottomright", lty=1, col=2:ncol(lemRoc), 
	legend=colnames(lemRoc)[-1], 
	title='threshold')
```

 

